# .github/workflows/deploy.yml
name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Yandex.Cloud S3
        uses: yandex-cloud/yc-s3-sync-action@v1
        with:
          yc-key-id: ${{ secrets.YC_KEY_ID }}
          yc-secret-key: ${{ secrets.YC_SECRET_KEY }}
          bucket: bpm-suite
          source: ./dist/
          delete: true
